#!/bin/sh

PYTHON_SITE_PACKAGES_DIR=/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/

if [ ! -d "$PYTHON_SITE_PACKAGES_DIR" ]; then
	echo "site-packages directory $PYTHON_SITE_PACKAGES_DIR does not exist." >&2
	exit 1
fi

platypus -a Chreditor \
	-o 'Text Window' \
	-i icons/emacs.icns \
	-f $PYTHON_SITE_PACKAGES_DIR/bottle.py \
	-f $PYTHON_SITE_PACKAGES_DIR/bottle.pyc \
	-f $PYTHON_SITE_PACKAGES_DIR/gevent \
	-f $PYTHON_SITE_PACKAGES_DIR/greenlet.so \
	-f $PYTHON_SITE_PACKAGES_DIR/yaml \
	-y \
	chreditor.py Chreditor.app

